name: better_life
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.17.4 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.7
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.1+1
  stylish_bottom_bar: ^0.1.3
  video_player: ^2.4.5
  google_fonts: ^3.0.1
  fluttertoast: ^8.0.9
  infinite_carousel: ^1.0.2
  animated_bottom_navigation_bar: ^1.0.1
  remixicon: ^1.0.0
  numeral: ^2.0.1
  auto_size_text: ^3.0.0
  readmore: ^2.2.0
  camera: ^0.10.0
  image_picker: ^0.8.5+3
  flutter_switch: ^0.3.2
  video_thumbnail: ^0.5.2
  video_editor: ^1.4.3
  helpers: ^1.1.4
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.0
  firebase_auth: ^3.5.0
  firebase_storage: ^10.3.4
  flutter_keyboard_visibility: ^5.3.0
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/navBarIcon/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/robotorobotoromanregular400.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/intersemibold400.ttf
          weight: 400
        - asset: assets/fonts/interbold700.ttf
          weight: 700
        - asset: assets/fonts/interregular400.ttf
          weight: 400
        - asset: assets/fonts/intermedium500.ttf
          weight: 500
        - asset: assets/fonts/interlight300.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppinsregular400.ttf
          weight: 400
